#
#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://3.110.168.165:3306/interview
#    username: root
#    password: Pass@word1
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
